project:
  type: website
  output-dir: docs
  resources:
    - info523-f23-syllabus.pdf
    - ./slides

website:
  page-navigation: true
  title: "INFO 523"
  description: "Homepage for INFO 523 - Data Mining and Discovery at The University of Arizona, Fall 2023."
  favicon: /images/logo.png

  repo-url: https://github.com/Gchism94/INFO523-F23
  repo-actions: [edit, issue]

  open-graph: true

  sidebar:
    background: "#EF4056" # AZ Red
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/INFO523DM
        text: "GitHub organization"
      - icon: code-square
        href: https://posit.cloud/
        text: "Posit Cloud"
      - icon: person-fill
        href: https://d2l.arizona.edu/d2l/home/1334579
        text: "D2L"
        menu:
          - text: Announcements
            href: https://datamineaz.slack.com
          - text: Zoom meetings
            href: https://arizona.zoom.us/my/gregchism
          - text: Gradebook
            href: https://d2l.arizona.edu/d2l/home/1334579

    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: course-team.qmd
            text: Teaching team
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
          - href: course-faq.qmd
            text: FAQ
          - href: tables/model-cheatsheet.qmd
            text: Model cheatsheet table
      - section: "Computing"
        contents:
          - href: computing/computing-troubleshooting.qmd
            text: Troubleshooting
          - href: computing/computing-cheatsheets.qmd
            text: Cheatsheets
          - href: computing/computing-git.qmd
            text: Setting up Git
      - section: "Slides"
        contents: 
          - href: slides/week1/Lec0Intro523.pdf
            text: Week 1 - Course Introduction
          - href: slides/week2/Lec1Intro523.pdf
            text: Week 2 - Intro to Data Mining
          - href: slides/week2/Lec1.2AdvancedRGitHubMarkdown.pdf
            text: Week 2 - Advanced R and GitHub
          - href: slides/week3/Lec2Data.pdf
            text: Week 3 - Intro to Data + Preprocessing
          - href: slides/week4/Lec3Exploration.pdf
            text: Week 4 - Preprocessing II + Data Viz I
          - href: slides/week6/Lec4BasicClassification.pdf
            text: Week 6 - Classification I
          - href: slides/week7/Lec5AlternativeClassification.pdf
            text: Week 7 - Classification II
          - href: slides/week8/Lect8_Regression.pdf
            text: Week 8 - Intro to Regression Models
          - href: slides/week9/Lec9Association.pdf
            text: Week 9 - Association Rules
      - section: "Readings"
        contents:
          - href: slides/week2/ch1DataMiningConceptual.pdf
            text: Chp 1 - Data Mining Conceptual
          - href: slides/week3/ch2DataMiningConceptual.pdf
            text: Chp 2 - Data Mining Conceptual
          - href: slides/week6/ch6.1_6.2_6.4-6.6_DataMiningConceptual.pdf
            text: Chps 6.2-6.2, 6.4-6.6 - Data Mining Conceptual
          - href: slides/week6/ch6.7_7.1_7.5DataMiningConceptual.pdf
            text: Chps 6.7, 7.1-7.5 - Data Mining Conceptual
          - href: slides/week8/ch3.1-3.5_6.1-6.2_7.1-7.3_8.2_ISLR.pdf
            text: Chps 3.1-3.5, 6.1-6.2, 7.1-7.3, 8.2 - ISRL
          - href: slides/week9/ch4DataMiningConceptual.pdf
            text: Chp 4 - Data Mining Conceptual
          - href: slides/week10/ch8.1_8.3DataMiningConceptual.pdf
            text: Chps 8.1-8.3 - Data Mining Conceptual
          - href: slides/week12/ch11_DataMiningConceptual.pdf
            text: Chp 11 - Data Mining Conceptual
          - href: slides/week13/ch1-2_practTimeSeries.pdf
            text: Chps 1-2 - Pract Time Series
          - href: slides/week15/ch3_practTimeSeries.pdf
            text: Chp 3 - Pract Time Series
          - href: slides/week16/Ch4_8IntroData MiningR.pdf
            text: Chapter 4-8 Intro Data Mining in R
      - section: "R Exercises"
        contents:
          - href: slides/week1/week1-2-R-tutorial.qmd
          - href: slides/week2/rExercise1.qmd
          - href: slides/week4/rExercise2.qmd
          - href: slides/week6/rExercise3.qmd
          - href: slides/week6/rExercise3_1.qmd
          - href: slides/week8/rExercise4.2.qmd
          - href: slides/week9/rExercise5.qmd
          - href: slides/week13/rExercise6.qmd
      - section: "Python Exercises"
        contents: 
          - href: python/pythonTutorial.ipynb
          - href: python/introPandasNumpy.ipynb
          - href: python/dataExplorationPython.ipynb
          - href: python/dataPreprocessingPython.ipynb
          - href: python/classificationPython.qmd
          - href: python/regressionPython.qmd
          - href: python/associationPython.qmd
      - section: "Homework"
        contents:
          - href: https://github.com/INFO-523-Exercises/r-python-exercise1
            text: HW 01
          - href: https://github.com/INFO-523-Exercises/hw-02
            text: HW 02
          - href: https://github.com/INFO-523-Exercises/hw-03
            text: HW 03
      - section: "Final Project"
        contents: 
          - href: project/project-2.qmd
            text: Final Project
          - href: project/project-tips-resources.qmd
            text: Tips & resources
            
  page-footer:
    right: "This page is built with 💛 and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Greg Chism"
    background: "#AB0520" # AZ Red

format:
  html:
    theme:
      light: [cosmo, style/info526.scss]
      dark: [cosmo, style/info526.scss, style/dark.scss]
    linkcolor: "#EF4056" # Azurite
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Montserrat"

execute:
  freeze: auto

editor: visual
